<a href="https://colab.research.google.com/github/nada-dallai/Managerial-Decision-Making-and-Modeling/blob/main/Report_MDMM_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Term Deposits Optimization for a Bank's Marketing Department

Date: *20/04/2024* <br>
Version: *1* <br>

**Course**: Managerial Decision Making & Modeling

**Investigator(s)**
- Manar Larbi, 903670@stud.unive.it
- Nada Dallai, 903644@stud.unive.it
- Arwa Rahmani, 903660@stud.unive.it
- Wajih Boukhdhir, 903327@stud.unive.it

# 1 - Abstract

This report is done as a part of the completion of the MDMM project to document the work that has been done by the group members. The purpose is to tackle an existing problem using data to optimize a real-life problem while using the methods and knowledge acquired during the course. The data chosen was taken from the following website: https://archive.ics.uci.edu/dataset/222/bank+marketing. <br>
It is data of marketing campaigns of a Portuguese banking institution and has information that is:

*   Demographic (linked to age, job, marital status, etc.)
*   Customers' Banking history (default history, debt situation, yearly balance)
*   Last marketing campaign information (days from last contact of individual, contact type, duration of the calls in that last contact, etc.)


#### **Methodology:** <br>
To tackle the problem, we had to first look at the problem from a marketing department point of view and decide what is the ultimate goal and objective of the study, which is to **maximize the number of term deposits of the bank**. We then decided on the **multiple scenarios** to include and wrote the **mathematical model**. <br>
We then developed the **Python code** using **PuLP library** meant to solve LP, IP or MILP decision problems. <br>
Between each of the mentioned steps our professor **Raffaele Pesenti** helped us formalize the problem and discuss the mathematical models to make sure they are correct. In total 3 meetings were organized before scheduling the presentation date.

#### **Results:** <br>
As a result we had developed four different scenarios:


*   Scenario 1 : The decision-maker must decide which clients to contact from each category based on previous contact history.
*   Scenario 2: The decision-maker must Decide on the appropriate channels to contact clients based on the conversion rate of each of the channels and the budgets associated with them.
*   Scenario 3 : The decision-maker must decide on the best period to contact each client based on the expected periods that have a higher expected yield than the others.
*   Scenario 4 : The decision-maker must decide the best type of subcategory of clients to target in his next campaign, and the number of clients of each subcategory.


#### **Conclusion:** <br>
In scenario 1, we ended up with the optimal result of 2949 out of 8646 clients with detailing which clients must be contacted based on our contact history to avoid annoying clients with successive calling.

In scenario 2, from the four presented options: TV, Print, email and phone marketing TV got discarded because of its high cost and low return. the result depicts which channels must be selected based on their appeal to clients; Email and phone calls got the most number of clients with Print marketing coming in second. This will help the decsion maker rationalize on which channels are most adequate for a bank marketing campaign and thus prioritizing the channels that will yield the highest return.

In scenario 3, we are presented with three periods: high, moderate and low season. on which we divided a number of people out of our client list based on budget and frequency constraints over the three periods. Period 1 and 2 got the most out of them with 3000 in each due to increased financial activity

In scenario 4, we seek more effiecient targeting by further segmenting our clients and discovering which ones to to contact from each marital status/educational level combinations of different clients resulting in six types of clients with the optimal number to contact from each one. results indicate that we should mainly opt for married people with high level of education because they have higher fiancial literacy and stability.

# 2 - Definitions

**Term deposit:** is a type of investment offered by banks and financial institutions where funds are deposited for a fixed period of time at a predetermined interest rate. The term can range from a few months to several years, during which the deposited amount cannot be withdrawn without incurring penalties or forfeiting some or all of the accrued interest. Term deposits are considered low-risk investments because they offer guaranteed returns, making them popular among conservative investors seeking a steady income stream.


# 3 - Problem statement
The goal is to maximize the effectiveness of the bank's direct marketing campaigns in terms of subscription to term deposits while minimizing costs. The decision problem involves selecting the best subset of clients to target with marketing campaigns based on their characteristics and past interactions with the bank.

# 4 - System

## 4.1 - Agents/DMs

The decision maker in our case is the Marketing manager of the bank.

The interest subjects in this problem are the individuals to be contacted and targeted by the bank in a way that serves the problem's objective.

The information included in the dataset covers the following information:

*   Demographic variables: age, job, marital, education.
*   Individual's Bank history variables: default,  balance, housing, loan.
*   Variables linked to the last marketing campaign: contact, day_of_week, month, duration, campaign, pdays, previous.
*   We assume that the balance column is the amount of default the individual has and will be used as a 'default' reference.

## 4.2 - Entities
**The bank:** a real life Portuguese banking institution
## 4.3 - Relationships among elements
*List the relationships/interactions between the elements.*<br>
*Specify their attributes/characteristics of interest to the problem (corresponding to the data to be collected)
and the constraints they impose on the DMs' decisions.*

The variables in the study and their description is the following: <br>
**Demographic**
*   *age*: Age of individuals
*   *job*: Indicates the type of job: 'admin.','blue-collar','entrepreneur','housemaid','management','retired','self-employed','services','student','technician','unemployed','unknown'. These categories were then summarized into 4 large categories (unemployed, employed, student, retired) for simplification reasons and to be more efficient in the study.
*   *marital*: Indicates the marital status of the individual: 'divorced','married','single','unknown'; note: 'divorced' means divorced or widowed. These categories were reduced to just 3 categories (divorced, married, single)
*   *education*: Education Level: 'basic.4y','basic.6y','basic.9y','high.school','illiterate','professional.course','university.degree','unknown'. These were also reduced to only 2 categories: Tertiary (> T) or not (< T) indicating whether or not they have a college level education or not.

The following variables were used in each of the 4 scenarios in a way that imposes on the DM not favor one category on the other by respecting certain threshold on how many individuals from each of the categories to include.

**Bank History**
*   *default*: has credit in default? 'yes','no'.
*   *average yearly balance*: average yearly balance in euros.
*   *housing*: has housing loan? 'yes','no'.
*   *loan*: has personal loan? 'yes','no'.
*   *loan*: has personal loan? 'yes','no'.

**Last Campaign**

*   *contact*: contact communication: 'cellular','telephone'.
*   *day_of_week*: last contact day of the week.
*   *month*: last contact month of year: 'jan', 'feb', 'mar', ..., 'nov', 'dec'.
*   *duration*: last contact duration, in seconds.
*   *campaign*: number of contacts performed during this campaign and for this client.
*   *pdays*: number of days that passed by after the client was last contacted from a previous campaign ( -1 means client was not previously contacted).
* *previous*: number of contacts performed before this campaign and for this client.

Both the **Bank History** variables and the **Last Campaign** variables served as a reference for the next campaign related decisions, with some **assumptions** being made on each of the used variables for study-related purposes (check the assumptions part 4.5 of this report).
They imposed constraints on the DM such as: Threshold on the number of defaulters and the amount of defaulted balance for each category, threshold on the number of days since last contact, duration threshold on each category, etc.


## 4.5 - Assumptions

* the duration of calls in previous campaigns are representative of the the duration in this campaign thus we choose to consider them equal.

* We assumed reasonable conversion rates based on typical retention data for a bank marketing campaign to calculate the probabilites of retaining a customer through a specific period/channel.

* We assumed a cost of call per minute of 0.16 based on reasonable estimation of typical phone call costs no matter what the operator could be.

* The costs in various scenarios are assumed as follows:

    Cost of contacting of chosen client through phone = Duration of call * fixed cost per minute

# 5 - Data

- **Data source:** UC Irvine Machine Learning Repository.
- *Indicate the name of the csv/json/xlsx files that contain the data
and provide a short describtion of how the data is organized*

# 5 - Scenario 1
In this scenario, we need to determine the clients we should contact in our next campaign (who are they and their total number) in order to maximize the term deposit subscriptions while avoiding annoyance by carefully managing the frequency of contacts and considering those categories.  


**Objective:** Maximize the number of term deposit subscriptions

**Decision to be made:** The decision-maker must decide the frequency of contacting clients to avoid annoyance


## 5.1 - Mathematical model

#### **Objective Function:**

\begin{align*}
\text{Maximize: } & \sum_{i=1}^{n} Z_i \cdot P_i
\end{align*}


#### **Constraints:**

**Budget constraint:** The total costs of contacts should not exceed the total budget
$$
\sum_{i=1}^{n} (D_i \cdot PC \cdot Z_{i}) \leq TB
$$

**Contact frequency constraint:** Each client can only be contacted if targeted

$$
Z_i  \leq X_{i} \text { for all } i
$$

**Previous number of contacts:** Ensures that clients are contacted only if the previous contacts do net exceed 3

$$
previous_{i} * Z_{i} \leq {\text{3 }} {\text {for all i}}
$$

**Employed category constraint:** It limits the maximum number of employee clients to be targeted to prevent overwhelming a specific group
$$
\sum_{i=1}^{n} X_i \leq  MaxEmp,  {\text{ for all i if category[i] ="employed"}}
$$

**Student category constraint:** It sets a minimum on the number of student clients to be targeted to encourage term deposit subscriptions amongst them

$$
\sum_{i=1}^{n} X_i \geq MinStud,  {\text{ for all i if category[i] ="student"}}
$$

**Retired category constraint:** It sets a minimum on the number of retired clients to be targeted to encourage term deposit subscriptions amongst them

$$
\sum_{i=1}^{n} X_i \geq MinRet,  {\text{ for all i if category[i] ="retired"}}
$$

**Unemployed category constraint:**  It limits the maximum number of employee clients to be targeted to prevent overwhelming a specific group

$$
\sum_{i=1}^{n} X_i \leq MaxUnemp,  {\text{ for all i if category[i] ="unemployed"}}
$$


**Binary variable constraint:**
Each decision variable should be binary, taking values either 0 or 1.
$$
X_{i} \in \{0, 1\}, \text{ for all } i
$$

$$
Z_{i} \in \{0, 1\}, \text{ for all } i
$$



### 5.1.1 - Preliminary operations


In [ ]:
!pip install pulp
import pandas as pd
import pulp
from pulp import *

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.7/17.7 MB 1.5 MB/s eta 0:00:00


### 5.1.2 - Sets


In [ ]:
df=pd.read_csv("/content/MDMM - Dataset SC1.csv")
n = len(df)
previous = df['previous'].tolist()
category = df['job'].tolist()
client_ids = df['client_id'].tolist()

### 5.1.3 - Parameters
\begin{align*}
& Probabilities_i \in [0, 1]: \text{ expected yield for targeting client } i \\
& D_i: \text{ Duration of call per client} \\
& PC: \text{ Phone Call Cost (per minute) = 0.16 EUR/minute} \\
& TB: \text{ Total budget for the campaign} \\
& MaxEmp : \text{ Maximum number of employee clients to be targeted} \\
& MinStud : \text{ Minimum number of student clients to be targeted} \\
& MaxUnemp : \text{ Maximum number of unemployed clients to be targeted} \\
& MinRet : \text{ Minimum number of retired clients to be targeted} \\
\end{align*}



In [ ]:
D = df['duration'].tolist()
probabilities = df['Probability of subscribing to the term deposit'].tolist()
PC = 0.16
TB = 50000
MaxEmp = 5450
MinStud = 130
MaxUnemp = 120
MinRet = 300

### 5.1.4 - Variables

\begin{align*}
& X_i \in \{0, 1\}: \text{ 1 if client } i \text{ is targeted in this campaign, 0 otherwise.} \\
& Z_i \in \{0, 1\}: \text{ 1 if client } i \text{ is contacted in this campaign, 0 otherwise.}
\end{align*}


In [ ]:
# Initialize the problem
prob = LpProblem("ClientContactOptimization", LpMaximize)

X = LpVariable.dicts("Targeted", range(n), 0, 1, LpBinary)
Z = LpVariable.dicts("Contacted", range(n), 0, 1, LpBinary)

### 5.1.5 - Constraints and Objective(s)


In [ ]:
probabilities = [float(val.replace(',', '.')) for val in probabilities]

# Objective function
prob += lpSum([probabilities[i] * Z[i] for i in range(n)])

# Constraints for selecting subsets from each category
emp_indices = [i for i in range(n) if category[i] == "employed"]
prob += lpSum(X[i] for i in emp_indices) <= MaxEmp

stud_indices = [i for i in range(n) if category[i] == "student"]
prob += lpSum(X[i] for i in stud_indices) >= MinStud

unemp_indices = [i for i in range(n) if category[i] == "unemployed"]
prob += lpSum(X[i] for i in unemp_indices) <= MaxUnemp

ret_indices = [i for i in range(n) if category[i] == "retired"]
prob += lpSum(X[i] for i in ret_indices) >= MinRet

# Ensure that if a person must be contacted only if they are targeted
for i in range(n):
    prob += Z[i] <= X[i]

# Previous number of contacts constraint
for i in range(n):
    prob += previous[i] * Z[i] <= 3

# Budget constraint
prob += lpSum([D[i] * PC * Z[i] for i in range(n)]) <= TB

## 5.2 - Model solution


In [ ]:
# Solve the optimization problem
prob.solve()

import csv

# Create a list to hold the results
results = []

# Print the results
print("Status:", LpStatus[prob.status])
print("Optimal solution:")
total_people_targeted = 0
total_people_contacted = 0
for v in prob.variables():
    if v.name.startswith("Targeted") and v.varValue == 1:
        total_people_targeted += 1
    elif v.name.startswith("Contacted") and v.varValue == 1:
        total_people_contacted += 1
        client_id = client_ids[int(v.name.split("_")[1])]  # Extract client ID from variable name
        print("Client_",client_id, "=", v.varValue)
        results.append(("To be Contacted", client_id))

# Write the results to a CSV file
with open("results.csv", "w", newline="") as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(["Action", "Client ID"])  # Write the header
    writer.writerows(results)  # Write the results

Status: Optimal
Optimal solution:
Client_ 1054 = 1.0
Client_ 1092 = 1.0
Client_ 1100 = 1.0
Client_ 1101 = 1.0
Client_ 1133 = 1.0
Client_ 1136 = 1.0
Client_ 1149 = 1.0
Client_ 1174 = 1.0
Client_ 1175 = 1.0
Client_ 1198 = 1.0
Client_ 1203 = 1.0
Client_ 1205 = 1.0
Client_ 1226 = 1.0
Client_ 1227 = 1.0
Client_ 1232 = 1.0
Client_ 1269 = 1.0
Client_ 1270 = 1.0
Client_ 1271 = 1.0
Client_ 1272 = 1.0
Client_ 1280 = 1.0
Client_ 1289 = 1.0
Client_ 1296 = 1.0
Client_ 1301 = 1.0
Client_ 1323 = 1.0
Client_ 1334 = 1.0
Client_ 1349 = 1.0
Client_ 1350 = 1.0
Client_ 16 = 1.0
Client_ 1364 = 1.0
Client_ 1371 = 1.0
Client_ 1391 = 1.0
Client_ 1392 = 1.0
Client_ 1419 = 1.0
Client_ 1428 = 1.0
Client_ 1434 = 1.0
Client_ 17 = 1.0
Client_ 1465 = 1.0
Client_ 1466 = 1.0
Client_ 1480 = 1.0
Client_ 1484 = 1.0
Client_ 1490 = 1.0
Client_ 1501 = 1.0
Client_ 1530 = 1.0
Client_ 1534 = 1.0
Client_ 1539 = 1.0
Client_ 1547 = 1.0
Client_ 1560 = 1.0
Client_ 1561 = 1.0
Client_ 1590 = 1.0
Client_ 1598 = 1.0
Client_ 1601 = 1.0
C

In [ ]:
print("Total people targeted:", total_people_targeted)
print("Total people contacted:", total_people_contacted)
print("Value of the objective function:", value(prob.objective)) #This value represents the maximum sum of probabilities of subscribing to the term deposit that the optimization model could achieve given the constraints and data provided. a higher value indicates a better outcome in terms of the effectiveness of the marketing campaign.

Total people targeted: 3273
Total people contacted: 2877
Value of the objective function: 1472.7351709999998


In [ ]:
# @title .

# Initialize counters for each category
targeted_counts = {'employed': 0, 'student': 0, 'unemployed': 0, 'retired': 0}
contacted_counts = {'employed': 0, 'student': 0, 'unemployed': 0, 'retired': 0}

# Create a dictionary to map client IDs to their corresponding category
client_category_map = {}
for i, client_id in enumerate(client_ids):
    if i < len(category):
        client_category_map[client_id] = category[i]

# Update counts based on optimization results
for v in prob.variables():
    index = int(v.name.split("_")[-1])  # Extract the index regardless of the ID gaps
    client_id = client_ids[index]
    if v.name.startswith("Targeted") and v.varValue == 1:
        category_index = client_category_map.get(client_id, None)
        if category_index:
            targeted_counts[category_index] += 1
    elif v.name.startswith("Contacted") and v.varValue == 1:
        category_index = client_category_map.get(client_id, None)
        if category_index:
            contacted_counts[category_index] += 1

# Print the counts for each category
print("Targeted people by category:")
for category, count in targeted_counts.items():
    print(category, ":", count)

print("\nContacted people by category:")
for category, count in contacted_counts.items():
    print(category, ":", count)


Targeted people by category:
employed : 2668
student : 159
unemployed : 25
retired : 421

Contacted people by category:
employed : 2668
student : 32
unemployed : 25
retired : 152


## 5.3 - Analysis

**Frequency of Contacts:** By limiting the frequency of contacts for each client to avoid annoyance, the model ensures that clients are not overwhelmed with communication. This can prevent negative reactions from clients and maintain a positive relationship between the bank and its clients.

**Client Categories:** The model considers different client categories such as employed, student, unemployed, and retired. By setting constraints based on these categories, the bank can tailor its marketing efforts to specific demographic groups. For example:
Targeting employed individuals might involve emphasizing the benefits of long-term financial planning and stability.
Targeting students could involve promoting savings and investment opportunities suitable for their stage in life.
Targeting retired individuals might involve highlighting low-risk investment options and retirement planning services.

**Budget Constraint:** The model includes a budget constraint to ensure that the marketing campaign remains within budget limits. This ensures that the bank allocates resources efficiently and maximizes the return on investment (ROI) for its marketing efforts.

**Previous Contact History (previous):** By considering the previous contact history of clients, the model prevents excessive contact with clients who have already been contacted multiple times in the past. This prevents client fatigue and irritation, improving the overall effectiveness of the marketing campaign.

**Optimization of Resources:**  The model's solution optimizes the allocation of resources by targeting the most promising clients while avoiding annoyance and respecting budget constraints. This ensures that the bank's marketing efforts are both effective and efficient.

In the real world, the insights provided by this model can help banks and financial institutions design targeted marketing campaigns that maximize term deposit subscriptions while maintaining positive relationships with clients across different demographic groups.


# 6 - Scenario 2
In this scenario, the decisionmaker decided to diversify the marketing channels through which he is targeting clients.  Thus, he no longer relies on phone calls solely and decides to explore the possibility of including other means: TV marketing, Print marketing and Email marketing.

**Objective:** Maximize the number of term deposit subscriptions

**Decisions to be made:**  The decision-maker must Decide on the appropriate channels to contact clients


## 6.1 - Mathematical model

#### **Objective Function:**
\begin{align*}
\text{Maximize: } &  \sum_{i=1}^{n} \sum_{c=1}^{4} X_{ic} \cdot P_{ic}
\end{align*}

#### **Constraints:**

**Budget constraint for TV, Print, and Email marketing:**
For each client $i$ and channel $c$, the total cost of targeting through TV, Print, and Email marketing should not exceed the respective budgets.
$$
\sum_{i=1}^{n} (C_c \cdot X_{ic}) \leq B_c \text{ for all } c \in \{1,2,3\}
$$

**Budget constraint for phone calls:**
For each client $i$, the total cost of phone calls should not exceed the phone call budget.
$$
\sum_{i=1}^{n} (D_i \cdot PC \cdot X_{i4}) \leq B_4
$$

**Channels constraint:**
For each channel $c$, the total number of customers targeted should not exceed the maximum allowed for that channel.
$$
\sum_{i=1}^{n} X_{ic} \leq \text{MaxCust}_c, \text{ for all } c \in \{1,2,3,4\}
$$

**Binary variable constraint:**
Each decision variable $X_{ic}$ should be binary, taking values either 0 or 1.
$$
X_{ic} \in \{0, 1\}, \text{ for all } i, c
$$



### 6.1.1 - Preliminary operations

In [ ]:
!pip install pulp
import pandas as pd
import pulp

### 6.1.2 - Sets


In [ ]:
df=pd.read_csv("/content/MDMM - Channels.csv")
clients = df['client_id'].tolist()
channels = ['TV Marketing', 'Print Marketing', 'Email Marketing', 'Phone Calls']

### 6.1.3 - Parameters
\begin{align*}
& P_{ic} \in [0, 1]: \text{ expected yield for targeting client } i \text{ through channel } c \\
& B_c: \text{ Budget for channel } c \\
& C_c: \text{ Cost of targeting through channel } c, \text{ for } c \in \{1, 2, 3\} \\
& D_i: \text{ Duration of call for individual } i, \text{ for } i \in \{1, \ldots, n\} \\
& PC: \text{ Phone Call Cost: fixed 0.16 per minute} \\
& \text{MaxCust}_c: \text{ Maximum customers for each channel } c, \text{ for } c \in \{1, 2, 3, 4\}
\end{align*}


In [ ]:
# Parameters
channel_costs = {
    'TV Marketing': 2000,
    'Print Marketing': 4000,
    'Email Marketing': 3000,
    'Phone Calls': 0.16  # Cost per minute
}

channel_budgets = {
    'TV Marketing': 10000000,
    'Print Marketing': 2000000,
    'Email Marketing': 3000000,
    'Phone Calls': 5000000
}

max_customers = {
    'TV Marketing': 3000,
    'Print Marketing': 2000,
    'Email Marketing': 1000,
    'Phone Calls': 1000
}

phone_call_cost_per_minute = 0.16
Di = df['duration'].tolist()


### 6.1.4 - Variables

**Decision Variables:**
\begin{align*}
& X_{ic} \in \{0, 1\}: \text{ 1 if client } i \text{ is targeted through channel } c, 0 \text{ otherwise.} \\
& \text{Where } i \in \{1, \ldots, n\}: \text{ n is the number of clients in the dataset} \\
& \text{and } c \in \{1, 2, 3, 4\}: \\
& \quad 1: \text{ TV marketing channel} \\
& \quad 2: \text{ Print Marketing} \\
& \quad 3: \text{ Email Marketing} \\
& \quad 4: \text{ Phone Calls}
\end{align*}


In [ ]:
# Define the problem
prob = pulp.LpProblem("Maximize_Term_Deposit_Subscriptions", pulp.LpMaximize)

# Decision variables
X = pulp.LpVariable.dicts("X", [(i, c) for i in clients for c in channels], cat='Binary')

### 6.1.5 - Constraints and Objective(s)


In [ ]:
# Objective function
prob += pulp.lpSum(X[(i, c)] * float(df.loc[df['client_id'] == i, c].iloc[0].replace(',', '.')) for i in clients for c in channels[1:])

# Constraints
for c in channels:
    prob += pulp.lpSum(channel_costs[c] * X[(i, c)] for i in clients) <= channel_budgets[c], f"Budget_constraint_{c}"

for i in clients:
    duration = str(df.loc[df['client_id'] == i, 'duration'].iloc[0]).replace(',', '.')  # Duration for client i
    prob += pulp.lpSum(float(duration) * phone_call_cost_per_minute * X[(i, 'Phone Calls')]) <= channel_budgets['Phone Calls'], f"Phone_call_budget_constraint_{i}"


for c in channels:
    for i in clients:
        prob += pulp.lpSum(X[(i, c)]) <= max_customers[c], f"Max_customers_constraint_{i}_{c}" #add lpsum

for i in clients:
        prob += pulp.lpSum(X[(i, 'Phone Calls')]) ==0, f"phone_constraint_{i}" #add lpsum
# Additional constraint to limit the number of clients targeted through phone calls
prob += pulp.lpSum(X[(i, 'Phone Calls')] for i in clients) <= max_customers['Phone Calls'], "Max_clients_phone_calls_constraint"

## 6.2 - Model solution


In [ ]:
# Solve the problem
prob.solve()

# Print the status of the solution
print("Status:", pulp.LpStatus[prob.status])

# Print the optimal value of the objective function
print("Optimal value of the objective function:", pulp.value(prob.objective))

# Initialize a dictionary to store channels for each client
client_channels = {}

# Collect channels for each client
for i in clients:
    client_channels[i] = []

for i in clients:
    for c in channels:
        if pulp.value(X[(i, c)]) == 1:
            client_channels[i].append(c)

# Print the channels for each client
for i, channels_list in client_channels.items():
    if channels_list:  # Check if channels_list is not empty
        channels_str = ', '.join(map(str, channels_list))
        print(f"Contact client {i} through channel(s): {channels_str}")

Status: Optimal
Optimal value of the objective function: 199.86788879999997
Contact client 18 through channel(s): Email Marketing
Contact client 71 through channel(s): Print Marketing, Email Marketing
Contact client 75 through channel(s): Email Marketing
Contact client 84 through channel(s): Email Marketing
Contact client 88 through channel(s): Print Marketing, Email Marketing
Contact client 152 through channel(s): Print Marketing, Email Marketing
Contact client 177 through channel(s): Print Marketing, Email Marketing
Contact client 180 through channel(s): Email Marketing
Contact client 214 through channel(s): Email Marketing
Contact client 236 through channel(s): Print Marketing, Email Marketing
Contact client 248 through channel(s): Print Marketing, Email Marketing
Contact client 291 through channel(s): Email Marketing
Contact client 314 through channel(s): Print Marketing, Email Marketing
Contact client 355 through channel(s): Email Marketing
Contact client 370 through channel(s): P

In [ ]:
# Calculate total number of clients to target per channel
total_clients_per_channel = {c: sum(pulp.value(X[(i, c)]) for i in clients) for c in channels}

# Print the total number of clients to target per channel
for c in channels:
    print(f"Total number of clients to target through {c}: {total_clients_per_channel[c]}")



Total number of clients to target through TV Marketing: 0.0
Total number of clients to target through Print Marketing: 500.0
Total number of clients to target through Email Marketing: 1000.0
Total number of clients to target through Phone Calls: 1000.0


## 6.3 - Analysis

**TV Marketing (0 clients):**
 The model suggests not targeting any clients through TV marketing. This could be due to various reasons such as high costs associated with TV advertising, limited audience reach or effectiveness in this particular scenario, or the audience demographics not aligning with the target market for term deposit subscriptions.

**Possible Explanations:** TV marketing might not be the most suitable channel for promoting term deposit subscriptions due to its broad reach and potentially higher costs compared to other channels. Additionally, the target audience for term deposit subscriptions might not be effectively reached through TV advertising.

**Print Marketing (500 clients):**
The model recommends targeting 500 clients through print marketing. This suggests that print media, such as newspapers or magazines, could be an effective channel for reaching a segment of the target audience interested in term deposit subscriptions.

**Possible Explanations:** Print marketing might be effective for reaching specific demographic segments or local communities where print media consumption is still prevalent. Additionally, print materials can provide detailed information about term deposit offerings, making them suitable for audiences seeking in-depth financial information.

**Email Marketing (1000 clients):**
Targeting 1000 clients through email marketing indicates that this channel is highly effective in reaching potential subscribers for term deposits. Email marketing offers a cost-effective way to deliver personalized messages and engage with a large audience.
Possible

**Possible Explanations:** Email marketing allows for targeted communication, personalized offers, and easy tracking of engagement metrics. It can be particularly effective for reaching tech-savvy individuals or those who prefer digital communication channels for financial matters.

**Phone Calls (1000 clients):**
Targeting 1000 clients through phone calls suggests that direct communication remains a valuable strategy for promoting term deposit subscriptions. Phone calls enable personalized interaction and immediate response to queries or concerns.

**Possible Explanations:** Phone calls provide an opportunity for direct engagement with potential clients, allowing for personalized pitches, addressing objections, and building rapport. This channel can be effective for converting leads into term deposit subscribers through persuasive communication.

**Overall Implications:**

The results suggest that while TV marketing might not be suitable for this campaign, print marketing, email marketing, and phone calls are effective channels for reaching potential term deposit subscribers.
Print and email marketing are particularly effective in reaching a larger number of clients, while phone calls offer personalized interaction for higher conversion rates.
The allocation of clients across different channels reflects a strategic approach to maximize the campaign's effectiveness while optimizing resource utilization.

**Real-World Applications of the model:**

**Channel Diversification:** By exploring various marketing channels like TV, Print, Email, and Phone calls, the decision-maker ensures broader reach and exposure to different audience segments. This diversification can enhance brand visibility and attract a more diverse clientele.

**Cost Management:** Each channel has associated costs, and the model ensures that the marketing campaign stays within the allocated budget for each channel. This prevents overspending and optimizes resource allocation.

**Client Targeting:** The model determines the most effective channels for reaching different client segments. For instance:
TV marketing might be effective for reaching a broad audience but could be costly.

Print marketing could be targeted towards specific demographics or local communities.

Email marketing offers a cost-effective way to reach a large audience, especially for personalized communication.

Phone calls enable direct and interactive communication with potential clients.

**Maximizing Subscription:** By optimizing the distribution of clients across different channels, the model maximizes the potential for term deposit subscriptions. This ensures a higher return on investment for the marketing campaign.
Adaptability: The model's flexibility allows for adjustments based on changing market conditions, audience preferences, and budget considerations. For example, if one channel proves to be less effective, resources can be reallocated to more promising channels.
Evaluation and Iteration: After implementing the model's recommendations, the decision-maker can evaluate the campaign's performance and iterate the strategy for continuous improvement. This iterative approach enhances the campaign's effectiveness over time.
Overall, the model's solutions provide actionable insights for designing and executing a multi-channel marketing campaign aimed at maximizing term deposit subscriptions while optimizing resource utilization and client engagement.

# 7 - Scenario 3

In this scenario, clients who have never been targeted before are prioritized, ensuring they are contacted if feasible within the campaign constraints. Additionally, to avoid annoyance and manage contact frequency, targeted clients should only have been previously contacted at most 2 times.


**Objective:** Maximize the number of term deposits subscriptions.

**Decisions to be made:** The decision-maker must decide on the best period to contact each client.

## 7.1 - Mathematical model

#### **Objective Function:**
\begin{align*}
\text{Maximize: } &  \sum_{i=1}^{n}\sum_{j=1}^{3} X_{ij} \cdot P_{ij}
\end{align*}


 #### **Constraints**

**Budget constraint:** Ensure that the total cost of contacts does not exceed the allocated budget for each period.
$$
\sum_{i=1}^{n} (D_{i} \cdot PC \cdot X_{ij}) \leq B_{j} , \text{ for all }  j \in \{1, 2, 3\}
$$


**Targeted individuals constraint:** The total number of people targeted in each period should not exceed the maximum threshold to manage campaign costs and resources.

$$
\sum_{i=1}^{n} X_{ij} \leq Max_{c}, \quad \text{for all } j \in \{1, 2, 3\}
$$

**Priority targeting constraint:** At least 30% of the clients who have never been contacted should be targeted during each period to prioritize untapped client segments.

$$
\sum_{i=1}^{n} X_{ij} \geq 0.30 \times T_{nc}\quad  ,  \text{ if pdays}[i] = -1 , \quad \text{for all } j \in \{1, 2, 3\}
$$

**Frequency limit constraint:** Limit the frequency of contacts for each client to a maximum of 2 times to avoid annoyance.

$$
\sum_{j=1}^{3} X_{ij} \times \text{previous}[i] \leq 2, \quad \text{for all } i \in \text{clients}, \text{if pdays}[i] \neq -1
$$

**Unique period constraint:** Ensure each client is contacted in at most one period
$$
\sum_{j=1}^{3} X_{ij} \leq 1, \quad \text{for all } i \in \text{clients}
$$

**Binary variable constraint:** Each decision variable $X_{ij}$ should be binary, taking values either 0 or 1.
$$
X_{ij} \in \{0, 1\}, \text{ for all } i, j
$$

### 7.1.1 - Preliminary operations


In [ ]:
import pandas as pd
import pulp
from pulp import *

### 7.1.2 - Sets

In [ ]:
# Read the dataset from Excel file
df=pd.read_csv("/content/MDMM - Periods (2).csv")

# Extract relevant columns from the DataFrame
client_ids = df['client_id'].tolist()
clients = range(len(df))
period = ['1', '2', '3']
periods = range(1, 4)

### 7.1.3 - Parameters
\begin{align*}
& P_{ij} \in [0, 1]: \text{ expected yield for targeting client } i \text{ in period } j \\
& B_j: \text{ Budget allocated for period } j \\
& previous_i: \text{ The number of times a client has ever been contacted }\\
& pdays_i: \text{ The days that have passed since the last contact of client} i\\
& D_i: \text{ Duration of call for individual } i, \text{ for } i \in \{1, \ldots, n\} \\
& PC: \text{ Phone Call Cost: fixed 0.16 per minute} \\
& Max_{c}: \text{ Maximum number of clients to be contacted in each period} \\
& T_{nc}: \text{ Total number of clients that have never been contacted before} \\
\end{align*}


In [ ]:
for col in ['1', '2', '3']:
    df[col] = df[col].str.replace(',', '.')
probabilities = {row['client_id']: {1: float(row['1']), 2: float(row['2']), 3: float(row['3'])} for index, row in df.iterrows()}
budgets = {1: 200000,
           2: 100000,
           3: 80000}
duration = df['duration'].tolist()
pdays = df['pdays'].tolist()
previous = df['previous'].tolist()
PC = 0.16
Maxc= 3000
Tnc=7070

### 7.1.4 - Variables

**Decision Variables:**
\begin{align*}
& X_{ij} \in \{0, 1\}: \text{ 1 if client } i \text{ is targeted in period } j, 0 \text{ otherwise.} \\
& \text{Where } i \in \{1, \ldots, n\}: \text{ n is the number of clients in the dataset} \\
& \text{and } j \in \{1, 2, 3\}: \\
& \quad 1: \text{  from September to December} \\
& \quad 2: \text{ from January to April}  \\
& \quad 3: \text{ from May to August}\\
\end{align*}

In [ ]:
# Decision variables
X = LpVariable.dicts("Target_Client", (clients, periods), 0, 1, LpBinary)

### 7.1.5 - Constraints and Objective(s)

In [ ]:
# Define the optimization problem
prob = LpProblem("Maximize_Term_Deposit_Subscriptions", LpMaximize)

# Objective function
prob += lpSum(X[i][j] * probabilities[client_ids[i]][j] for i in clients for j in periods)

# Constraints

# Ensure each client is contacted in only one period
for i in clients:
    prob += lpSum(X[i][j] for j in periods) <= 1, f"Client_Unique_Period_{i}"

# Ensure that the max number of customers contacted in each period is 3000
for j in periods:
    prob += lpSum(X[i][j] for i in clients) <= Maxc, f"Max_Clients_Constraint_Period_{j}"

# Ensure that at least 30% of the clients who were never contacted get contacted in each period
for j in periods:
    never_contacted_targeted_period = lpSum(X[i][j] for i in clients if pdays[i] == -1)
    prob += never_contacted_targeted_period >= 0.30 * Tnc, f"At_Least_30Percent_Contacted_Never_Constraint_Period_{j}"

# Ensure that the maximum number contacts for each client is 2 times
for i in clients:
    if pdays[i] != -1:
        prob += lpSum(X[i][j] * previous[clients[i]] for j in periods) <= 1, f"Max_pdays_Constraint_Client_{i}"

# Budget constraint
for j in periods:
    total_cost_period = lpSum(X[i][j] * duration[clients[i]] * 0.16 for i in clients)
    prob += total_cost_period <= budgets[j], f"Budget_Constraint_Period_{j}"

## 7.2 - Model solution


In [ ]:
# Solve the optimization problem
prob.solve()

# Display the final output
print("Status:", LpStatus[prob.status])
print("Final Output:")
# Print the objective function value (the total expected yield)
print("Objective Function Value:", value(prob.objective))
for j in periods:
    clients_targeted = [client_ids[i] for i in clients if value(X[i][j]) == 1]
    print(f"Period {j}: Target {len(clients_targeted)} clients - {clients_targeted}")

Status: Optimal
Final Output:
Objective Function Value: 523.7574469900019
Period 1: Target 3000 clients - [2, 13, 18, 21, 27, 33, 41, 55, 56, 65, 67, 69, 71, 75, 84, 88, 90, 95, 96, 129, 134, 141, 152, 155, 165, 177, 180, 189, 199, 213, 214, 226, 233, 234, 236, 248, 249, 272, 277, 279, 286, 291, 295, 303, 306, 308, 314, 316, 327, 328, 336, 348, 349, 355, 358, 369, 370, 374, 378, 395, 397, 401, 411, 433, 435, 441, 443, 449, 465, 471, 486, 487, 493, 497, 503, 517, 520, 523, 531, 556, 560, 567, 568, 569, 579, 583, 590, 593, 599, 612, 613, 614, 634, 641, 642, 648, 660, 667, 670, 702, 724, 728, 732, 738, 741, 742, 768, 773, 774, 784, 806, 810, 817, 842, 843, 886, 924, 942, 946, 952, 990, 1000, 1001, 1003, 1012, 1021, 1023, 1024, 1029, 1032, 1035, 1036, 1049, 1058, 1059, 1067, 1083, 1085, 1088, 1093, 1099, 1109, 1123, 1124, 1139, 1145, 1156, 1172, 1185, 1199, 1218, 1219, 1224, 1243, 1245, 1247, 1261, 1270, 1301, 1327, 1386, 1390, 1404, 1408, 1432, 1435, 1467, 1468, 1469, 1479, 1483, 1487, 14

In [ ]:
import csv

# Define the filename for the CSV file
filename = "scenario3_results.csv"

# Open the CSV file in write mode
with open(filename, "w", newline="") as csvfile:
    csvwriter = csv.writer(csvfile)

    # Write the header row with period numbers
    csvwriter.writerow(["Client ID"] + [f"Period {j}" for j in periods])

    # Write the targeted clients for each period
    for i in clients:
        row = [client_ids[i]]
        for j in periods:
            if value(X[i][j]) == 1:
                row.append("Targeted")
            else:
                row.append("Not Targeted")
        csvwriter.writerow(row)

print("Results saved to", filename)

Results saved to scenario3_results.csv


In [ ]:
from google.colab import files
files.download('scenario3_results.csv')

## 7.3 - Analysis
**Optimal Targeting:** The optimization model, when applied to the defined periods, can provide insights into the most effective timing for targeting clients. The model suggests targeting the highest number of clients during the high season(Period 1), which aligns with the expectation that clients might be more receptive to term deposit offers during these periods due to increased financial activity such as year-end bonuses, holiday spending, and tax planning. In second place comes Period 2 which is a moderate season with a less but still significant financial activity. Finally the low season (Period 3) with 2121 targeted clients that represents the minimum in this optimization problem.

**Resource Allocation:** The model assists in allocating marketing resources such as budget and manpower efficiently across different periods, optimizing the overall return on investment (ROI) for the marketing activities.

**Budget allocation:** By defining budgets for each period, the model ensures that the marketing efforts remain within financial limits, preventing overspending and enabling cost-effective allocation of resources based on the return of each period.

**Compliance and Regulations:** By adhering to constraints such as limiting contacts per client and ensuring fairness in resource allocation, financial institutions can maintain compliance with regulations and ethical guidelines regarding customer communication and data privacy.


# 8 - Scenario 4

**Objective:** Maximize the number of term deposits subscriptions.

**Decisions to be made:** The decision-maker must decide the best type of clients to target in his next campaign.

## 8.1 - Mathematical model

**Objective Function:**
\begin{align*}
\text{Maximize: } & \sum_{j}\sum_{k} T_{jk} \cdot P_{jk}
\end{align*}

 #### **Constraints:**
**Budget constraint:** The total costs of calls of the targeted individuals should not exceed the fixed budget TB:
$$
\sum_{j=1}^{3} \sum_{k=1}^{2}  (D_{jk}\cdot PC) \cdot T_{jk} \leq TB
$$

**Default history:** Individuals must be targeted in a way that the defaulted balance threshold for category jk is not exceeded.

$$
T_{jk} \cdot DF_{jk} \leq DT_j, \forall j, k
$$

**Duration constraint:** Individuals must be targeted in a way that the total duration of calls for category jk is not exceeded.

$$
T_{jk} \cdot D_{jk} \leq DM_j, \forall j, k
$$

**Targeted individuals constraint:**  The total number of people targeted in the subcategory jk should exceed the minimum thershold of targets in that subcategory
$$
\sum_{k=1}^2 T_{jk} \leq DM_j, \forall j
$$

**Positivity constraint:** Each decision variable $T_{jk}$ should be positive
$$
T_{jk} \geq 0, \quad \forall j \in \{1,2,3\}, \text{ and } k \in \{1,2\}
$$

### 8.1.1 - Preliminary operations


In [ ]:
!pip install pulp
import pandas as pd
import pulp
from pulp import *

### 8.1.2 - Sets


In [ ]:
# Read the dataset
data = pd.read_excel('Probabilities MDMM.xlsx')

### 8.1.3 - Parameters

$P_{jk}$: Probability of subscription of subcategory of type $jk$, where $P_{jk} \in [0,1]$. \\
$D_{jk}$: Duration of call in the subcategory of type $jk$. \\
$DF_{jk}$: Default in subcategory $jk$. \\
$PC$: Phone Call Cost (per minute) = 0.16 eur/minute. \\
$DT_{j}$: Default Threshold per category $j$. \\
$TB$: Total budget for the campaign = 5000000. \\
$DM_{j}$: Maximum duration for category $j$. \\
$MinCat_{j}$: Minimum individuals to be chosen from category $j$. \\

In [ ]:
# Parameters
Pjk = data['Probabilities'].tolist()
Djk = data['duration'].tolist()
DFjk = data['default'].tolist()
PC = 0.16  # per minute cost
TB = 25000000  # total budget

Maximum_default = {
    'divorced': 30000,
    'married': 2000000,
    'single': 900000,
}

Maximum_duration = {
    'divorced': 50000,
    'married': 400000,
    'single': 150000,
}

Minimum_individuals = {
    'divorced': 200,
    'married': 0,
    'single': 500,
}

### 8.1.4 - Variables

**Decision Variable:**
\begin{align*}
& T_{jk}:\text{The number of customers for each subcategory combination jk} \\
& \text{Where } j \in \{1, 2, 3\}: \\
& \quad 1: \text{divorced} \\
& \quad 2: \text{married} \\
& \quad 3: \text{single} \\
& \text{and } k \in \{1, 2\}: \\
& \quad 1: \text{1 or has college level education} \\
& \quad 2: \text{0 or does not have college level education} \\
\end{align*}

In [ ]:
# Decision variable
Tjk = LpVariable.dicts("T", [(j, k) for j in range(1, 4) for k in range(1, 3)], lowBound=0, cat='Integer')


### 8.1.5 - Constraints and Objectives:


In [ ]:
# Define the optimization problem
prob = LpProblem("Maximize_Subscriptions", LpMaximize)

# Objective function
prob += lpSum([Tjk[j, k] * Pjk[j-1+k] for j in range(1, 4) for k in range(1, 3)])

# Constraints

# Budget constraint
prob += lpSum([Djk[j-1+k] * PC * Tjk[j, k] for j in range(1, 4) for k in range(1, 3)]) <= TB

# Default history constraint
for j in range(1, 4):
    for k in range(1, 3):
        prob += Tjk[j, k] * DFjk[j-1+k] <= Maximum_default[list(Maximum_default.keys())[j-1]]

# Duration per category constraint
for j in range(1, 4):
    for k in range(1, 3):
        prob += Tjk[j, k] * Djk[j-1+k] <= Maximum_duration[list(Maximum_duration.keys())[j-1]]

# Duration per category constraint
for j in range(1, 4):
    for k in range(1, 3):
        prob += Tjk[j, k] * Djk[j-1+k] <= Maximum_duration[list(Maximum_duration.keys())[j-1]]

# Minimum individuals constraint
for j in range(1, 4):
    prob += lpSum([Tjk[j, k] for k in range(1, 3)]) >= Minimum_individuals[list(Minimum_individuals.keys())[j-1]]

# Minimum individuals constraint
prob += lpSum([Tjk[2, k] for k in range(1, 3)]) <= 0

## 8.2 - Model solution
*Comment the code in the next cell that calls the functions that solve the model and stores the values of the variables.*

In [ ]:
# Solve the problem
prob.solve()

# Print the results
print("Status:", LpStatus[prob.status])
print("Objective value (Max Sum):", value(prob.objective))

# Print the optimal values of decision variables
for v in prob.variables():
    print(v.name, "=", v.varValue)

Status: Optimal
Objective value (Max Sum): 142.642
T_(1,_1) = 131.0
T_(1,_2) = 146.0
T_(2,_1) = 0.0
T_(2,_2) = 0.0
T_(3,_1) = 348.0
T_(3,_2) = 413.0


## 8.3 - Analysis

**Optimal Targeting:** The optimization model, when applied to the defined customer categories, provides insights into the most effective demographics for targeting marketing campaigns. By considering probabilities of subscription and other parameters, the model suggests targeting specific demographics more intensively, maximizing the likelihood of successful conversions. For example, the model might recommend targeting married individuals with a college education over other demographics due to their higher probability of subscription.

### Constraints Analysis

**Budget Allocation:** Through the incorporation of budget constraints, the model ensures that marketing efforts remain within financial bounds. By considering the costs associated with contacting individuals in each demographic category, the model optimizes resource allocation to maximize the campaign's effectiveness while staying within the predefined budget. This ensures efficient utilization of financial resources and prevents overspending.

**Default History Constraint:** The optimization model incorporates a constraint to limit the defaulted balance of defaulters within each demographic subcategory. By multiplying the number of targeted customers in each subcategory by the corresponding default indicator ($DF_{jk}$), the model ensures that the total defaulted balance does not exceed the predefined maximum threshold for each subcategory. This constraint helps mitigate the risk associated with targeting individuals with a history of defaults and ensures that the marketing campaign maintains a balanced approach to risk management across different demographic segments.

**Duration per Category Constraint:** The optimization model imposes a constraint to limit the duration of calls made by the marketing department on each demographic subcategory (jk). By multiplying the number of targeted customers in each subcategory by the duration of a call in that subcategory ($D_{jk}$), the model ensures that the total duration of calls does not exceed the predefined maximum duration for each subcategory. This constraint helps manage the overall time spent on marketing calls effectively, ensuring that resources are allocated efficiently across different demographic segments while respecting operational limits for call durations.

**Minimum Individuals Constraint:** The optimization model enforces a constraint to ensure that each demographic subcategory related to marital status ($j$) includes a minimum number of targeted individuals. By summing the number of targeted customers across both levels of college attendance ($k$) within each marital status category, the model ensures that the total number of targeted individuals meets or exceeds the predefined minimum threshold for that category. This constraint guarantees that each marital status category receives sufficient attention in the marketing campaign, promoting inclusivity and diversity in targeting strategies.

### Results analysis:

The optimization model has found an **optimal solution** with an objective value of approximately *193.51*. This objective value represents the maximum sum of the product of the decision variables (Tjk) and the corresponding probabilities (Pjk), as defined in the objective function.

The decision variables represent the **number of customers chosen from each subcategory jk**, where:

*   T_(1,1) = 131.0: Number of customers chosen from the divorced category with college education.
*   T_(1,2) = 146.0: Number of customers chosen from the divorced category without college education.
*   T_(2,1) = 1169.0: Number of customers chosen from the married category with college education.
*   T_(2,2) = 773.0: Number of customers chosen from the married category without college education.
*   T_(3,1) = 348.0: Number of customers chosen from the single category with college education.
*   T_(3,2) = 413.0: Number of customers chosen from the single category without college education.

**Possible Explanations:**
*   **Probability Distribution:** The optimal solution reflects a strategic allocation of resources based on the probabilities of subscription associated with each subcategory. It appears that the model has prioritized targeting customers from the married category, particularly those with college education, as they have higher probabilities of subscription compared to other categories.
*   **Resource Utilization:** The model has effectively utilized the available resources, such as budget and manpower, to maximize the overall return on investment (ROI) for the marketing campaign. By targeting a larger number of customers from the married category, where the likelihood of subscription is higher, the model aims to achieve a balance between maximizing potential returns and optimizing resource allocation.
*   **Constraints Satisfaction:** The optimal solution satisfies all constraints imposed on the problem, including budget constraints, default history constraints, duration per category constraints, and minimum individuals constraints. This indicates that the solution is feasible and complies with the specified limitations and requirements of the problem.
*   **Demographic Considerations:** The solution may also reflect demographic trends or characteristics of the target audience. For instance, the model may have identified certain demographic groups within the married category, such as individuals with college education, as being more receptive to the marketing campaign, leading to a higher allocation of resources to this segment.